name: Fetch GitHub Data

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *' # Executa a cada hora

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Fetch GitHub Repos and User Data
        env:
          PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
        run: |
          curl -H "Authorization: token $PERSONAL_TOKEN" "https://api.github.com/users/WesleyS08/repos?sort=created&direction=desc" > repos.json
          curl -H "Authorization: token $PERSONAL_TOKEN" "https://api.github.com/users/WesleyS08" > user.json

      - name: Commit JSON data
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add repos.json user.json
          git commit -m 'Update GitHub data'
          git push
